from internals.configuration import Config

config = Config(
    # start_page="https://example.com",
    # start_page='https://codeby.games/categories/web/cdd2d7e7-495e-4a14-b0ea-cae75b7b21a3',
    # start_page='http://62.173.140.174:16000/',
    # start_page='https://www.wolframalpha.com/',
    # start_page='https://palchevsky.ru/',
    # start_page='https://palchevsky.ru/awards.php',
    # start_page='https://palchevsky.ru/r.php?r=https://www.elibrary.ru/item.asp?id=38251321',
    # start_page='https://gettransfer.com/ru',
    # start_page='https://mephi.ru/',
    # start_page='https://www.xvideos.com/',
    # start_page='https://vk.com/wtblog',
    # start_page='https://www.desmos.com/calculator?lang=ru',
    start_page='https://dashakudryavtseva.com/',
    maximum_recursion_depth=3,
    browser='Firefox',
    wait_time=15,
    printout=True,
    log=False,
    pickle_dump_file_name='./data/pickle_blog-l3',
    graph_file_name='result_blog-l3.html',
    mode='strict',
    cookies=False,
)
